"""Generate a Markdown day-report from the current data sources.

Output: `data/reports/YYYY-MM-DD.md`. Idempotent — overwrites the
file each time it's called, so re-running through the day produces
the freshest snapshot of today's narrative. Running post-sunset
(after the daily_summary row flips to complete) produces the
authoritative final report.

Pulls from:
    today_harvest.snapshot()       — live numbers + peaks + forecast hx
    daily_summary.csv (today row)  — day-total Ah / weather joins
    calibration_log.csv            — SolarModel coefficient changes

CLI:
    python scripts/end_of_day_report.py            # today
    python scripts/end_of_day_report.py --date 2026-05-18
"""

from __future__ import annotations

import argparse
import csv
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import today_harvest as today_harvest_mod  # noqa: E402
import calibration_log as calibration_log_mod  # noqa: E402
import projection_log as projection_log_mod  # noqa: E402
import projection_accuracy as projection_accuracy_mod  # noqa: E402
import solar_onset as solar_onset_mod  # noqa: E402
import confidence_log as confidence_log_mod  # noqa: E402


def _f(v) -> Optional[float]:
    if v in (None, "", "None"):
        return None
    try:
        return float(v)
    except ValueError:
        return None


def _load_daily_row(daily_csv: Path, day: date) -> Optional[dict]:
    """Find the daily_summary row matching `day`. Returns the row dict
    (string values), or None if not present yet."""
    if not daily_csv.exists():
        return None
    target = day.isoformat()
    try:
        with daily_csv.open() as f:
            for r in csv.DictReader(f):
                if r.get("date") == target:
                    return r
    except Exception:
        return None
    return None


def _fmt(v, suffix: str = "", places: int = 1) -> str:
    """Format a value (might be string or float) for the report.
    Returns '—' for None/empty."""
    if v in (None, "", "None"):
        return "—"
    try:
        f = float(v)
        return f"{f:.{places}f}{suffix}"
    except (TypeError, ValueError):
        return str(v) + suffix


def _build_summary_sentence(snap: dict, daily_row: Optional[dict]) -> str:
    """One-line lede summarizing the day. Adapts to whether we have a
    complete daily_summary row or just the partial today_harvest."""
    pct = snap.get("pct_of_forecast")
    drift = None
    coef = snap.get("solar_ah_forecast")
    live_r = snap.get("live_ratio_ah_per_kwh_m2")
    if live_r is not None and snap.get("solar_ah_forecast") is not None:
        # coef is in (Ah / kWh-m²) by way of solar_ah_forecast / irradiance
        pass

    parts = []
    if pct is not None:
        if pct >= 110:
            parts.append(f"harvest **{pct:.0f}% of forecast** — strong day")
        elif pct >= 90:
            parts.append(f"harvest **{pct:.0f}% of forecast** — on track")
        elif pct >= 50:
            parts.append(f"harvest **{pct:.0f}% of forecast** — soft day")
        else:
            parts.append(f"harvest **{pct:.0f}% of forecast** — well below")

    if daily_row is not None:
        partial = (daily_row.get("partial", "True").lower() in ("true", "1", "yes"))
        net = _f(daily_row.get("net_ah"))
        if net is not None:
            sign = "+" if net >= 0 else "−"
            parts.append(f"net **{sign}{abs(net):.1f} Ah** to the pack")
        if not partial:
            parts.insert(0, "**Complete day**:")
        else:
            parts.insert(0, "*(partial day so far)*")

    if not parts:
        return "Day in progress."
    return " — ".join(parts) + "."


def _model_changes_for_day(day: date) -> list:
    """Return the calibration_log entries that landed on `day`."""
    entries = calibration_log_mod.read_log()
    out = []
    target = day.isoformat()
    for e in entries:
        if e.ts.startswith(target):
            out.append(e)
    return out


def build_report(day: date) -> str:
    """Generate the Markdown report text for `day`. Returns the string;
    caller decides whether to write to disk."""
    pack_csv = Path("data/pack.csv")
    weather_csv = Path("data/weather.csv")
    daily_csv = Path("data/daily_summary.csv")

    snap = today_harvest_mod.snapshot(pack_csv, weather_csv, today=day)
    daily_row = _load_daily_row(daily_csv, day)
    model_changes = _model_changes_for_day(day)

    lines: list[str] = []
    lines.append(f"# Day report — {day.isoformat()} (Loon Lake)")
    lines.append("")
    lines.append("_Generated by `scripts/end_of_day_report.py`. Idempotent — "
                 "re-runs overwrite this file with the latest snapshot._")
    lines.append("")

    summary = _build_summary_sentence(snap, daily_row)
    lines.append(f"**Summary**: {summary}")
    lines.append("")

    # ---------- Pack ----------
    lines.append("## Pack")
    lines.append("")
    if daily_row is not None:
        lines.append(f"- SOC walk: **{_fmt(daily_row.get('soc_start'),'%',0)} "
                     f"→ {_fmt(daily_row.get('soc_end'),'%',0)}** "
                     f"(range "
                     f"{_fmt(daily_row.get('soc_min'),'%',0)}–"
                     f"{_fmt(daily_row.get('soc_max'),'%',0)})")
        lines.append(f"- Charge: **+{_fmt(daily_row.get('charge_ah'),' Ah')}**, "
                     f"discharge: −{_fmt(daily_row.get('discharge_ah'),' Ah')}, "
                     f"net: {_fmt(daily_row.get('net_ah'),' Ah')}")
        g_min = _f(daily_row.get("generator_minutes")) or 0.0
        if g_min > 0:
            lines.append(f"- Generator: **{g_min:.0f} min** "
                         f"⇒ {_fmt(daily_row.get('generator_ah'),' Ah')}")
        else:
            lines.append("- Generator: not run today")
    else:
        lines.append(f"- Duration so far: {snap['duration_h']:.1f} h, "
                     f"{snap['samples']} samples")

    # Peaks
    pk = snap.get("peaks") or {}
    pk_lines = []
    if pk.get("peak_charge_a") is not None:
        pk_lines.append(f"peak charge **{pk['peak_charge_a']:.1f} A**")
    if pk.get("peak_smoothed_a") is not None:
        pk_lines.append(f"peak smoothed **{pk['peak_smoothed_a']:.1f} A**")
    if pk.get("peak_soc_pct") is not None:
        pk_lines.append(f"peak SOC **{pk['peak_soc_pct']:.0f}%**")
    if pk.get("peak_pack_voltage_v") is not None:
        pk_lines.append(f"peak pack voltage **{pk['peak_pack_voltage_v']:.2f} V**")
    if pk_lines:
        lines.append(f"- Peaks: {', '.join(pk_lines)}")
    if pk.get("first_charge_time"):
        lines.append(f"- First net charging at **{pk['first_charge_time']}**")

    lines.append("")

    # ---------- Solar harvest ----------
    lines.append("## Solar harvest")
    lines.append("")
    lines.append(f"- Solar Ah harvested: **{_fmt(snap.get('solar_ah_so_far'),' Ah')}** "
                 f"({_fmt(snap.get('pct_of_forecast'),'%',0)} of forecast)")
    if snap.get("irradiance_kwh_m2_forecast") is not None:
        lines.append(f"- Forecast irradiance: "
                     f"**{snap['irradiance_kwh_m2_forecast']:.2f} kWh/m²**")
    if snap.get("irradiance_kwh_m2_so_far") is not None:
        lines.append(f"- Actual irradiance delivered: "
                     f"**{snap['irradiance_kwh_m2_so_far']:.2f} kWh/m²**")
    if snap.get("live_ratio_ah_per_kwh_m2") is not None:
        lines.append(f"- Live ratio (latest): "
                     f"**{snap['live_ratio_ah_per_kwh_m2']:.2f} Ah/(kWh/m²)**")

    # ---------- Solar onset ----------
    # The morning cascade — when each milestone of the discharge-to-
    # charge transition was observed. Reads from data/solar_onset.csv
    # if a row exists for this day, otherwise scans pack.csv directly.
    # The latter is the path for re-running on a historical day before
    # the log was retroactively backfilled.
    lines.append("")
    lines.append("## Solar onset")
    lines.append("")
    try:
        # Prefer the logged row (idempotent across reruns), but fall
        # back to fresh detection if missing.
        logged = {r.date: r for r in solar_onset_mod.read_log()}
        rec = logged.get(day.isoformat())
        if rec is None:
            rec = solar_onset_mod.detect_onset(Path("data/pack.csv"), day)
    except Exception:
        rec = solar_onset_mod.SolarOnsetRecord(date=day.isoformat())

    if rec.is_empty():
        lines.append("No solar onset detected — pack stayed in discharge "
                     "all day (heavy cloud, or system shut down before "
                     "morning, or the report is being generated pre-dawn).")
    else:
        def _short(iso: Optional[str]) -> str:
            return iso[11:19] if (iso and "T" in iso) else "—"

        lines.append("| milestone | timestamp |")
        lines.append("|-----------|-----------|")
        lines.append(f"| first zero crossing (pack_i = 0) | "
                     f"{_short(rec.first_zero_iso)} |")
        lines.append(f"| first idle (state=idle or \\|i\\| ≤ 0.5 A) | "
                     f"{_short(rec.first_idle_iso)} |")
        lines.append(f"| first positive current (pack_i > 0) | "
                     f"{_short(rec.first_positive_iso)} |")
        lines.append(f"| first net-positive (smoothed_i > 0) | "
                     f"{_short(rec.first_net_positive_iso)} |")
        lines.append("")
        if rec.first_net_positive_iso is not None:
            smi = (f"**{rec.smoothed_i_at_net_positive:+.2f} A**"
                   if rec.smoothed_i_at_net_positive is not None else "—")
            soc = (f"**{rec.soc_avg_at_net_positive:.1f} %**"
                   if rec.soc_avg_at_net_positive is not None else "—")
            lines.append(f"At net-positive crossover: smoothed current "
                         f"{smi}, pack SOC (avg) {soc} — this is the "
                         f"bottom of the day's SOC curve and a useful "
                         f"calibration check against the advisor's "
                         f"`projected_low_soc`.")
        elif rec.first_zero_iso is not None:
            lines.append("Net-positive crossover still pending — solar "
                         "managed to offset load briefly but hasn't yet "
                         "sustained net charging.")
    lines.append("")

    # ---------- Weather ----------
    fh = snap.get("forecast_history") or {}
    lines.append("")
    lines.append("## Weather")
    lines.append("")
    if daily_row is not None:
        if daily_row.get("weather_kwh_m2"):
            lines.append(f"- Day-total horizontal irradiance: "
                         f"**{_fmt(daily_row.get('weather_kwh_m2'),' kWh/m²',2)}**")
        if daily_row.get("weather_cloud_pct_avg"):
            lines.append(f"- Mean cloud cover: "
                         f"**{_fmt(daily_row.get('weather_cloud_pct_avg'),'%',0)}**")
        t_min = _f(daily_row.get("weather_temp_c_min"))
        t_max = _f(daily_row.get("weather_temp_c_max"))
        if t_min is not None and t_max is not None:
            lines.append(f"- Temperature range: **{t_min:.1f} – {t_max:.1f} °C**")
    if fh.get("n"):
        drift = fh.get("drift_pct")
        drift_str = f"{drift:+.1f}%" if drift is not None else "—"
        swing = None
        if fh.get("first") and fh.get("min") is not None and fh.get("max") is not None:
            swing = (fh["max"] - fh["min"]) / fh["first"] * 100.0
        swing_str = f"{swing:.1f}%" if swing is not None else "—"
        lines.append(f"- Open-Meteo forecast revisions: "
                     f"{fh.get('first'):.2f} → {fh.get('latest'):.2f} kWh/m² "
                     f"(drift {drift_str}, swing {swing_str}, n={fh['n']})")

    lines.append("")

    # ---------- Model state ----------
    lines.append("## SolarModel state")
    lines.append("")
    if model_changes:
        lines.append(f"Calibration_log entries for {day.isoformat()}:")
        lines.append("")
        lines.append("| timestamp | coef | n_obs | confidence | source |")
        lines.append("|-----------|-----:|------:|-----------:|--------|")
        for e in model_changes:
            short_ts = e.ts[11:16] if len(e.ts) >= 16 else e.ts
            lines.append(f"| {short_ts} | {e.coefficient:.3f} | "
                         f"{e.n_observations} | {e.confidence} | {e.source} |")
    else:
        lines.append("No SolarModel coefficient changes logged today.")
    lines.append("")

    # ---------- Projection accuracy ----------
    # For projections whose sunrise_iso fell within `day`, compare what
    # the advisor predicted against what actually happened in pack.csv.
    # Pairs with the dashboard's /accuracy page.
    lines.append("## Projection accuracy")
    lines.append("")
    try:
        all_proj = projection_log_mod.read_log()
        pack_samples = projection_accuracy_mod._load_pack_samples(
            Path("data/pack.csv"))
        # Filter projections whose sunrise_iso fell in `day` — i.e. the
        # projections that PREDICTED something about the sunrise on
        # this report's day.
        day_proj = [p for p in all_proj
                    if p.sunrise_iso.startswith(day.isoformat())]
        records = projection_accuracy_mod.compute_accuracy_records(
            day_proj, pack_samples)
    except Exception:
        records = []

    if records:
        s = projection_accuracy_mod.summarize(records)
        lines.append(f"{len(records)} projection{'s' if len(records) != 1 else ''} "
                     f"targeting **{day.isoformat()} sunrise** validated against "
                     f"actual SOC. Mean error **{s['mean_error']:+.1f} pp**, "
                     f"abs **{s['mean_abs_error']:.1f}**, RMS "
                     f"**{s['rms_error']:.1f}**.")
        lines.append("")
        lines.append("| made at | projected | actual | error (pp) |")
        lines.append("|---------|----------:|-------:|-----------:|")
        for r in records:
            short_made = (r.projection_ts[:16] if len(r.projection_ts) >= 16
                          else r.projection_ts)
            sign = "+" if r.error_pct_points >= 0 else "−"
            lines.append(f"| {short_made} | {r.projected_sunrise_soc:.1f} | "
                         f"{r.actual_sunrise_soc:.1f} | "
                         f"{sign}{abs(r.error_pct_points):.1f} |")

        # By-lead-time-horizon breakdown — the same view the dashboard
        # /accuracy page shows. Day-reports are the long-term archive
        # so historical days carry this signal even after data
        # accumulates and the live dashboard rolls past. Skipped when
        # no records (handled by the outer `if records`).
        by_h = projection_accuracy_mod.summarize_by_horizon(records)
        if by_h:
            lines.append("")
            lines.append("### By lead-time horizon")
            lines.append("")
            lines.append("How error varies with how far ahead each projection "
                         "was made. A consistent shape (e.g. optimistic far "
                         "out, pessimistic close in) is the strongest signal "
                         "of model-fit bias to track over time.")
            lines.append("")
            lines.append("| horizon | n | mean (pp) | abs (pp) | rms (pp) | range (pp) |")
            lines.append("|---------|--:|----------:|---------:|---------:|-----------:|")
            for b in by_h:
                lines.append(
                    f"| {b['bucket']} | {b['n']} | "
                    f"{b['mean_error']:+.2f} | "
                    f"{b['mean_abs_error']:.2f} | "
                    f"{b['rms_error']:.2f} | "
                    f"[{b['min_error']:+.2f}..{b['max_error']:+.2f}] |"
                )
    else:
        lines.append("No validatable projections for this day yet — "
                     "the first record lands at the next sunrise after the "
                     "projection_log starts collecting.")
    lines.append("")

    # ---------- Confidence-lift events ----------
    # The advisor's accuracy-aware confidence lift fires when the
    # recent projection_accuracy track record is tight. Transitions
    # are logged to data/confidence_log.csv; surface ones that
    # happened on this day so the report carries the timeline.
    lines.append("## Confidence-lift events")
    lines.append("")
    try:
        all_lifts = confidence_log_mod.read_log()
        day_lifts = [e for e in all_lifts
                     if e.ts.startswith(day.isoformat())]
    except Exception:
        day_lifts = []

    if day_lifts:
        lines.append(f"{len(day_lifts)} confidence-state transition"
                     f"{'s' if len(day_lifts) != 1 else ''} on this day. "
                     f"Each row marks a moment when (base, resolved, lifted) "
                     f"differed from the previous logged state — stable "
                     f"runs are deduped.")
        lines.append("")
        lines.append("| timestamp | base | resolved | lifted? | "
                     "recent abs err (pp) | recent n | source |")
        lines.append("|-----------|------|----------|---------|"
                     "--------------------:|---------:|--------|")
        for e in day_lifts:
            ts_short = e.ts[11:19] if "T" in e.ts and len(e.ts) >= 19 else e.ts
            ae = ("—" if e.recent_abs_error_pp is None
                  else f"{e.recent_abs_error_pp:.2f}")
            lifted = "**yes**" if e.lifted else "no"
            lines.append(
                f"| {ts_short} | {e.base} | {e.resolved} | {lifted} | "
                f"{ae} | {e.recent_n} | {e.source} |"
            )
        # Summary line capturing what the day's net effect was on
        # confidence — useful for the archive reader.
        first = day_lifts[0]
        last = day_lifts[-1]
        if first.resolved != last.resolved or first.lifted != last.lifted:
            lines.append("")
            lines.append(f"Net: started day at **{first.resolved}** "
                         f"(lifted={first.lifted}), ended at "
                         f"**{last.resolved}** (lifted={last.lifted}).")
    else:
        lines.append("No confidence-state transitions on this day — the "
                     "advisor's resolved tier and lift status held steady. "
                     "(See `data/confidence_log.csv` for the most recent "
                     "prior transition.)")
    lines.append("")

    # ---------- Cross-refs ----------
    lines.append("## Cross-references")
    lines.append("")
    lines.append(f"- Loop notes for the day: see `docs/STATUS.md` § Loop notes "
                 f"(entries dated {day.isoformat()})")
    lines.append("- Pack data: `data/pack.csv`")
    lines.append("- Weather data: `data/weather.csv`")
    lines.append("- Daily summary row: `data/daily_summary.csv`")
    lines.append("- Calibration log: `data/calibration_log.csv`")
    lines.append("- Projection log: `data/projection_log.csv`")
    lines.append("- Solar onset log: `data/solar_onset.csv`")
    lines.append("- Confidence-lift log: `data/confidence_log.csv`")
    lines.append("")

    return "\n".join(lines) + "\n"


def write_report(day: date, out_dir: Path = Path("data/reports")) -> Path:
    """Generate and write the report for `day` to `out_dir`. Returns
    the path written."""
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{day.isoformat()}.md"
    path.write_text(build_report(day))
    return path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", default=None,
                    help="ISO date to report on (default: today)")
    ap.add_argument("--stdout", action="store_true",
                    help="print to stdout instead of writing to file")
    args = ap.parse_args()

    if args.date:
        day = date.fromisoformat(args.date)
    else:
        day = datetime.now().date()

    if args.stdout:
        print(build_report(day))
    else:
        path = write_report(day)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
